AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stock-price-movement

  SAM Template for stock-price-movement

Globals:
  Function:
    Timeout: 3

Resources:
  CloudWatchEvent:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(5 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt EventQueue.Arn
          Id: "EventQueue"
          InputTransformer:
            InputPathsMap:
              time: "$.time"
            InputTemplate: '{"message": "<time>"}'
  
  EventQueue:
    Type: AWS::SQS::Queue
  
  EventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EventQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - events.amazonaws.com
            Action: 
              - sqs:SendMessage
            Resource: !GetAtt EventQueue.Arn
        
  ApiPollingFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: api_polling/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EventQueue.Arn
            BatchSize: 10
      Policies:
        - DynamoDBCrudPolicy: 
            TableName:
              !Ref StockPriceTable
        - SQSPollerPolicy:
            QueueName:
              !Ref EventQueue
  
  StockPriceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: Date
        Type: String
  
  MovementDetectingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: movement_detecting/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy: 
            TableName:
              !Ref StockPriceTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MovementSNSTopic.TopicName
  
  MovementSNSTopic:
    Type: AWS::SNS::Topic
  
Outputs:
  MovementSNSTopicArn:
    Value: !Ref MovementSNSTopic